# Generated by Django 5.0.4 on 2024-05-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Web', 'Web'), ('Application', 'Application'), ('AI', 'AI'), ('Data Analysis', 'Data Analysis'), ('Web Scraping', 'Web Scraping')], max_length=50),
        ),
    ]
