# Generated by Django 5.0.4 on 2024-05-22 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_maincategory_remove_category_super_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main', to='blog.maincategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub', to='blog.subcategory'),
        ),
    ]
