# Generated by Django 5.0.4 on 2024-05-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_main_category_blog_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=None)),
                ('discreption', models.TextField()),
                ('backgroun', models.TextField()),
                ('team_work', models.TextField()),
                ('our_core_value', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name_plural': 'Main categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub categories'},
        ),
    ]
