# Generated by Django 5.0.4 on 2024-05-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_about_alter_maincategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='backgroun',
            new_name='background',
        ),
    ]
